name: auto-cr action

on:
  pull_request:
    branches:
      - main

permissions:
  contents: 'write'
  id-token: 'write'
  pull-requests: write
  issues: 'write'

jobs:
  AutoCR:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Install NPM dependencies
        run: pnpm i -g @yiliang114/zhinang-cr-bot
      - name: Auto CR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZHINANG_TOKEN: ${{ secrets.ZHINANG_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          NODE_ENV: production
        run: zhinang cr $PR_NUMBER --zhinang-token $ZHINANG_TOKEN --owner $OWNER --repo $REPO
